//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.Entity.Core.Objects;
using System.Linq;
using Ministry.RepoLayer.ObjContext.Abstract;

namespace Ministry.RepoLayer.ObjContext.Repositories
{
	/// <summary>
	/// Provides access to the Categories from the data source.
	/// </summary>
	public partial class CategoriesRepository : RepositoryBase<IEdmxContextWrapper, Category, Category, int>, ICategoriesRepository
	{
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoriesRepository"/> class.
        /// </summary>
        /// <param name="contextWrapper">The context wrapper.</param>
        public CategoriesRepository(IEdmxContextWrapper contextWrapper)
            : base(contextWrapper)
        { }
		
        /// <summary>
        /// Gets the entity set.
        /// </summary>
        protected override IObjectSet<Category> EntitySet
        {
            get { return Context.Categories; }
        }
		
        /// <summary>
        /// Gets the set of data to query against.
        /// </summary>
        protected override IQueryable<Category> QuerySet
        {
            get { return EntitySet; }
        }

        /// <summary>
        /// Gets the Category by id.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>Category</returns>
        public override Category ById(int id)
        {
            var query = QuerySet.FirstOrDefault(x => x.Id == id);
            return query;
        }
	}
}
