//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.Entity.Core.Objects;
using Ministry.RepoLayer.ObjContext.Abstract;

namespace Ministry.RepoLayer.ObjContext
{
    /// <summary>
    /// Wraps the Edmx Entity Framework Context.
    /// </summary>
    public class EdmxContextWrapper : ContextWrapperBase<EdmxEntities>, IEdmxContextWrapper
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdmxContextWrapper"/> class.
        /// </summary>
        public EdmxContextWrapper()
        {
            Context = new EdmxEntities();
        }
		
    	/// <summary>
        /// Gets the Projects entities.
        /// </summary>
        public IObjectSet<Project> Projects { get { return Context.Projects; } }
		
    	/// <summary>
        /// Gets the Responses entities.
        /// </summary>
        public IObjectSet<Response> Responses { get { return Context.Responses; } }
		
    	/// <summary>
        /// Gets the Categories entities.
        /// </summary>
        public IObjectSet<Category> Categories { get { return Context.Categories; } }
		
    }
}
