//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ministry.RepoLayer.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action : Response
    {
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PlannedStart { get; set; }
        public Nullable<System.DateTime> PlannedFinish { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> ActualFinish { get; set; }
    }
}
