//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Objects;
using Ministry.RepoLayer.DbContext.Abstract;

namespace Ministry.RepoLayer.DbContext
{
    /// <summary>
    /// Wraps the Edm Entity Framework Context.
    /// </summary>
    public class EdmContextWrapper : ContextWrapperBase<EdmEntities>, IEdmContextWrapper
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdmContextWrapper"/> class.
        /// </summary>
        public EdmContextWrapper()
        {
            Context = new EdmEntities();
        }
		
    	/// <summary>
        /// Gets the Categories entities.
        /// </summary>
        public IDbSet<Category> Categories { get { return Context.Categories; } }
		
    	/// <summary>
        /// Gets the Projects entities.
        /// </summary>
        public IDbSet<Project> Projects { get { return Context.Projects; } }
		
    	/// <summary>
        /// Gets the Responses entities.
        /// </summary>
        public IDbSet<Response> Responses { get { return Context.Responses; } }
		
    }
}
