//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Objects;

namespace Ministry.RepoLayer.DbContext.Abstract
{
    /// <summary>
    /// Wrapping interface for the Edm Entity Framework Context.
    /// </summary>
    public interface IEdmContextWrapper : IContextWrapper
    {
    	IDbSet<Category> Categories { get; }
    	IDbSet<Project> Projects { get; }
    	IDbSet<Response> Responses { get; }
    }
}
