//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ministry.RepoLayer.DbContext.Abstract
{
	/// <summary>
	/// Interface to provide access to the Categories from the data source.
	/// </summary>
	public partial interface ICategoriesRepository : IRepository<Category, int>
	{	}

	/// <summary>
	/// Interface to provide access to the Projects from the data source.
	/// </summary>
	public partial interface IProjectsRepository : IRepository<Project, System.Guid>
	{	}

	/// <summary>
	/// Interface to provide access to the Responses from the data source.
	/// </summary>
	public partial interface IResponsesRepository : IRepository<Response, System.Guid>
	{	}

	/// <summary>
	/// Interface to provide access to the Actions from the data source.
	/// </summary>
	public partial interface IActionsRepository : IRepository<Action, System.Guid>
	{	}

	/// <summary>
	/// Interface to provide access to the Observations from the data source.
	/// </summary>
	public partial interface IObservationsRepository : IRepository<Observation, System.Guid>
	{	}

	/// <summary>
	/// Interface to provide access to the Risks from the data source.
	/// </summary>
	public partial interface IRisksRepository : IRepository<Risk, System.Guid>
	{	}

	
}
