//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ministry.RepoLayer.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Response> Responses { get; set; }
    }
}
