//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ministry.RepoLayer.DbContext.Repositories;

namespace Ministry.RepoLayer.DbContext.Abstract
{
    /// <summary>
    /// Provides Repository Implementations
    /// </summary>
    public abstract class RepositoryFactoryBase : IRepositoryFactory
    {
		#region | Repositories |

		/// <summary>
        /// Gets the Category repository implementation.
        /// </summary>
        public ICategoriesRepository Categories { get; protected set; }		
		/// <summary>
        /// Gets the Project repository implementation.
        /// </summary>
        public IProjectsRepository Projects { get; protected set; }		
		/// <summary>
        /// Gets the Response repository implementation.
        /// </summary>
        public IResponsesRepository Responses { get; protected set; }		
		/// <summary>
        /// Gets the Action repository implementation.
        /// </summary>
        public IActionsRepository Actions { get; protected set; }		
		/// <summary>
        /// Gets the Observation repository implementation.
        /// </summary>
        public IObservationsRepository Observations { get; protected set; }		
		/// <summary>
        /// Gets the Risk repository implementation.
        /// </summary>
        public IRisksRepository Risks { get; protected set; }		
		#endregion

        /// <summary>
        /// Gets or sets the context.
        /// </summary>
        protected IEdmContextWrapper Context { get; set; }

        /// <summary>
        /// Binds the repositories.
        /// </summary>
        /// <param name="contextWrapper">The context wrapper.</param>
        protected void BindRepositories(IEdmContextWrapper contextWrapper)
        {
            Context = contextWrapper;
			
        	Categories = new CategoriesRepository(Context);		
        	Projects = new ProjectsRepository(Context);		
        	Responses = new ResponsesRepository(Context);		
        	Actions = new ActionsRepository(Context);		
        	Observations = new ObservationsRepository(Context);		
        	Risks = new RisksRepository(Context);		
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public virtual void Dispose()
        {		
        	if (Categories != null) Categories.Dispose();		
        	if (Projects != null) Projects.Dispose();		
        	if (Responses != null) Responses.Dispose();		
        	if (Actions != null) Actions.Dispose();		
        	if (Observations != null) Observations.Dispose();		
        	if (Risks != null) Risks.Dispose();		
        }

        /// <summary>
        /// Saves the current context state to the database.
        /// </summary>
        public void Save()
        {
            Context.SaveChanges();
        }

        /// <summary>
        /// Accepts all changes made to the underlying context.
        /// </summary>
        public void AcceptAllChanges()
        {
            Context.AcceptAllChanges();
        }

		/// <summary>
        /// Dumps and refreshes the underlying context, abandoning any outstanding changes.
        /// </summary>
        public virtual void Refresh()
		{
			Context.Dispose();
		    Context = new EdmContextWrapper();
		    BindRepositories(Context);
		}
    }
}
