//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ministry.RepoLayer.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<short> Priority { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Project Project { get; set; }
    }
}
