//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Objects;
using System.Linq;
using Ministry.RepoLayer.DbContext.Abstract;

namespace Ministry.RepoLayer.DbContext.Repositories
{
	/// <summary>
	/// Provides access to the Responses from the data source.
	/// </summary>
	public partial class ResponsesRepository : RepositoryBase<IEdmContextWrapper, Response, Response, System.Guid>, IResponsesRepository
	{
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponsesRepository"/> class.
        /// </summary>
        /// <param name="contextWrapper">The context wrapper.</param>
        public ResponsesRepository(IEdmContextWrapper contextWrapper)
            : base(contextWrapper)
        { }
		
        /// <summary>
        /// Gets the entity set.
        /// </summary>
        protected override IDbSet<Response> EntitySet
        {
            get { return Context.Responses; }
        }
		
        /// <summary>
        /// Gets the set of data to query against.
        /// </summary>
        protected override IQueryable<Response> QuerySet
        {
            get { return EntitySet; }
        }

        /// <summary>
        /// Gets the Response by id.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>Response</returns>
        public override Response ById(System.Guid id)
        {
            var query = QuerySet.FirstOrDefault(x => x.Id == id);
            return query;
        }
	}
}
