//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Entities", "FK_Responses_Actions", "Action", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ministry.RepoLayer.ObjContext.Action), "Respons", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ministry.RepoLayer.ObjContext.Response), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Responses_Projects", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ministry.RepoLayer.ObjContext.Project), "Respons", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ministry.RepoLayer.ObjContext.Response), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Responses_Risks", "Risk", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ministry.RepoLayer.ObjContext.Risk), "Respons", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ministry.RepoLayer.ObjContext.Response), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Responses_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ministry.RepoLayer.ObjContext.Category), "Response", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ministry.RepoLayer.ObjContext.Response), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Responses_Observations", "Observation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ministry.RepoLayer.ObjContext.Observation), "Response", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ministry.RepoLayer.ObjContext.Response), true)]

#endregion

namespace Ministry.RepoLayer.ObjContext
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EdmxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EdmxEntities object using the connection string found in the 'EdmxEntities' section of the application configuration file.
        /// </summary>
        public EdmxEntities() : base("name=EdmxEntities", "EdmxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EdmxEntities object.
        /// </summary>
        public EdmxEntities(string connectionString) : base(connectionString, "EdmxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EdmxEntities object.
        /// </summary>
        public EdmxEntities(EntityConnection connection) : base(connection, "EdmxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Response> Responses
        {
            get
            {
                if ((_Responses == null))
                {
                    _Responses = base.CreateObjectSet<Response>("Responses");
                }
                return _Responses;
            }
        }
        private ObjectSet<Response> _Responses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Responses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResponses(Response response)
        {
            base.AddObject("Responses", response);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Action : Response
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Action object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectId">Initial value of the ProjectId property.</param>
        public static Action CreateAction(global::System.Guid id, global::System.Guid projectId)
        {
            Action action = new Action();
            action.Id = id;
            action.ProjectId = projectId;
            return action;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value, "DueDate");
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DueDate;
        partial void OnDueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedStart
        {
            get
            {
                return _PlannedStart;
            }
            set
            {
                OnPlannedStartChanging(value);
                ReportPropertyChanging("PlannedStart");
                _PlannedStart = StructuralObject.SetValidValue(value, "PlannedStart");
                ReportPropertyChanged("PlannedStart");
                OnPlannedStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedStart;
        partial void OnPlannedStartChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedFinish
        {
            get
            {
                return _PlannedFinish;
            }
            set
            {
                OnPlannedFinishChanging(value);
                ReportPropertyChanging("PlannedFinish");
                _PlannedFinish = StructuralObject.SetValidValue(value, "PlannedFinish");
                ReportPropertyChanged("PlannedFinish");
                OnPlannedFinishChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedFinish;
        partial void OnPlannedFinishChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedFinishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActualStart
        {
            get
            {
                return _ActualStart;
            }
            set
            {
                OnActualStartChanging(value);
                ReportPropertyChanging("ActualStart");
                _ActualStart = StructuralObject.SetValidValue(value, "ActualStart");
                ReportPropertyChanged("ActualStart");
                OnActualStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActualStart;
        partial void OnActualStartChanging(Nullable<global::System.DateTime> value);
        partial void OnActualStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActualFinish
        {
            get
            {
                return _ActualFinish;
            }
            set
            {
                OnActualFinishChanging(value);
                ReportPropertyChanging("ActualFinish");
                _ActualFinish = StructuralObject.SetValidValue(value, "ActualFinish");
                ReportPropertyChanged("ActualFinish");
                OnActualFinishChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActualFinish;
        partial void OnActualFinishChanging(Nullable<global::System.DateTime> value);
        partial void OnActualFinishChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Category CreateCategory(global::System.Int32 id)
        {
            Category category = new Category();
            category.Id = id;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Responses_Categories", "Response")]
        public EntityCollection<Response> Responses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Response>("Entities.FK_Responses_Categories", "Response");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Response>("Entities.FK_Responses_Categories", "Response", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Observation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Observation : Response
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Observation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectId">Initial value of the ProjectId property.</param>
        public static Observation CreateObservation(global::System.Guid id, global::System.Guid projectId)
        {
            Observation observation = new Observation();
            observation.Id = id;
            observation.ProjectId = projectId;
            return observation;
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Project CreateProject(global::System.Guid id)
        {
            Project project = new Project();
            project.Id = id;
            return project;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Responses_Projects", "Respons")]
        public EntityCollection<Response> Responses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Response>("Entities.FK_Responses_Projects", "Respons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Response>("Entities.FK_Responses_Projects", "Respons", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Response")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Action))]
    [KnownTypeAttribute(typeof(Risk))]
    [KnownTypeAttribute(typeof(Observation))]
    public partial class Response : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Response object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectId">Initial value of the ProjectId property.</param>
        public static Response CreateResponse(global::System.Guid id, global::System.Guid projectId)
        {
            Response response = new Response();
            response.Id = id;
            response.ProjectId = projectId;
            return response;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProjectId
        {
            get
            {
                return _ProjectId;
            }
            set
            {
                OnProjectIdChanging(value);
                ReportPropertyChanging("ProjectId");
                _ProjectId = StructuralObject.SetValidValue(value, "ProjectId");
                ReportPropertyChanged("ProjectId");
                OnProjectIdChanged();
            }
        }
        private global::System.Guid _ProjectId;
        partial void OnProjectIdChanging(global::System.Guid value);
        partial void OnProjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value, "Sequence");
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value, "CategoryId");
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryId;
        partial void OnCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value, "ModifiedDate");
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, "Priority");
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int16> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int16> value);
        partial void OnPriorityChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Responses_Projects", "Project")]
        public Project Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("Entities.FK_Responses_Projects", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("Entities.FK_Responses_Projects", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("Entities.FK_Responses_Projects", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("Entities.FK_Responses_Projects", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Responses_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Entities.FK_Responses_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Entities.FK_Responses_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Entities.FK_Responses_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("Entities.FK_Responses_Categories", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Responses_Observations", "Observation")]
        public Observation Observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("Entities.FK_Responses_Observations", "Observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("Entities.FK_Responses_Observations", "Observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> ObservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("Entities.FK_Responses_Observations", "Observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("Entities.FK_Responses_Observations", "Observation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Risk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Risk : Response
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Risk object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectId">Initial value of the ProjectId property.</param>
        public static Risk CreateRisk(global::System.Guid id, global::System.Guid projectId)
        {
            Risk risk = new Risk();
            risk.Id = id;
            risk.ProjectId = projectId;
            return risk;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Liklihood
        {
            get
            {
                return _Liklihood;
            }
            set
            {
                OnLiklihoodChanging(value);
                ReportPropertyChanging("Liklihood");
                _Liklihood = StructuralObject.SetValidValue(value, "Liklihood");
                ReportPropertyChanged("Liklihood");
                OnLiklihoodChanged();
            }
        }
        private Nullable<global::System.Int32> _Liklihood;
        partial void OnLiklihoodChanging(Nullable<global::System.Int32> value);
        partial void OnLiklihoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Impact
        {
            get
            {
                return _Impact;
            }
            set
            {
                OnImpactChanging(value);
                ReportPropertyChanging("Impact");
                _Impact = StructuralObject.SetValidValue(value, "Impact");
                ReportPropertyChanged("Impact");
                OnImpactChanged();
            }
        }
        private Nullable<global::System.Int32> _Impact;
        partial void OnImpactChanging(Nullable<global::System.Int32> value);
        partial void OnImpactChanged();

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Entities", Name="LocalMatch")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class LocalMatch : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LocalMatch object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="servings">Initial value of the Servings property.</param>
        /// <param name="timeInSeconds">Initial value of the TimeInSeconds property.</param>
        public static LocalMatch CreateLocalMatch(global::System.Int32 id, global::System.Int32 recipeId, global::System.Int32 servings, global::System.Int32 timeInSeconds)
        {
            LocalMatch localMatch = new LocalMatch();
            localMatch.Id = id;
            localMatch.RecipeId = recipeId;
            localMatch.Servings = servings;
            localMatch.TimeInSeconds = timeInSeconds;
            return localMatch;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                OnRecipeIdChanging(value);
                ReportPropertyChanging("RecipeId");
                _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                ReportPropertyChanged("RecipeId");
                OnRecipeIdChanged();
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Servings
        {
            get
            {
                return _Servings;
            }
            set
            {
                OnServingsChanging(value);
                ReportPropertyChanging("Servings");
                _Servings = StructuralObject.SetValidValue(value, "Servings");
                ReportPropertyChanged("Servings");
                OnServingsChanged();
            }
        }
        private global::System.Int32 _Servings;
        partial void OnServingsChanging(global::System.Int32 value);
        partial void OnServingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeInSeconds
        {
            get
            {
                return _TimeInSeconds;
            }
            set
            {
                OnTimeInSecondsChanging(value);
                ReportPropertyChanging("TimeInSeconds");
                _TimeInSeconds = StructuralObject.SetValidValue(value, "TimeInSeconds");
                ReportPropertyChanged("TimeInSeconds");
                OnTimeInSecondsChanged();
            }
        }
        private global::System.Int32 _TimeInSeconds;
        partial void OnTimeInSecondsChanging(global::System.Int32 value);
        partial void OnTimeInSecondsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IngredientsList
        {
            get
            {
                return _IngredientsList;
            }
            set
            {
                OnIngredientsListChanging(value);
                ReportPropertyChanging("IngredientsList");
                _IngredientsList = StructuralObject.SetValidValue(value, true, "IngredientsList");
                ReportPropertyChanged("IngredientsList");
                OnIngredientsListChanged();
            }
        }
        private global::System.String _IngredientsList;
        partial void OnIngredientsListChanging(global::System.String value);
        partial void OnIngredientsListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true, "Source");
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true, "Tags");
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags = "";
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Colour
        {
            get
            {
                return _Colour;
            }
            set
            {
                OnColourChanging(value);
                ReportPropertyChanging("Colour");
                _Colour = StructuralObject.SetValidValue(value, "Colour");
                ReportPropertyChanged("Colour");
                OnColourChanged();
            }
        }
        private global::System.Int32 _Colour = 0;
        partial void OnColourChanging(global::System.Int32 value);
        partial void OnColourChanged();

        #endregion

    }

    #endregion

}
