//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Objects;

namespace Ministry.RepoLayer.ObjContext.Abstract
{
    /// <summary>
    /// Wrapping interface for the Edmx Entity Framework Context.
    /// </summary>
    public interface IEdmxContextWrapper : IContextWrapper
    {
    	IObjectSet<Project> Projects { get; }
    	IObjectSet<Response> Responses { get; }
    	IObjectSet<Category> Categories { get; }
    }
}
