//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Linq;
using Ministry.RepoLayer.ObjContext.Abstract;

namespace Ministry.RepoLayer.ObjContext.Repositories
{
	/// <summary>
	/// Provides access to the Risks from the data source.
	/// </summary>
	public partial class RisksRepository : RepositoryBase<IEdmxContextWrapper, Risk, Response, System.Guid>, IRisksRepository
	{
        /// <summary>
        /// Initializes a new instance of the <see cref="RisksRepository"/> class.
        /// </summary>
        /// <param name="contextWrapper">The context wrapper.</param>
        public RisksRepository(IEdmxContextWrapper contextWrapper)
            : base(contextWrapper)
        { }
		
        /// <summary>
        /// Gets the entity set.
        /// </summary>
        protected override IObjectSet<Response> EntitySet
        {
            get { return Context.Responses; }
        }
		
        /// <summary>
        /// Gets the set of data to query against.
        /// </summary>
        protected override IQueryable<Risk> QuerySet
        {
            get { return EntitySet.OfType<Risk>(); }
        }

        /// <summary>
        /// Gets the Risk by id.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>Risk</returns>
        public override Risk ById(System.Guid id)
        {
            var query = QuerySet.FirstOrDefault(x => x.Id == id);
            return query;
        }
	}
}
